### ISSUE TITLE
can not use bsdiff-node in worker_threads

### ISSUE THREAD

**Issue by zpbc007** [Brouilles/bsdiff-node#19]
Hi there..

I try to use bsdiff-node  in nodejs worker_threads，but got the error : " Module did not self-register."

```bash
[Nest] 76026  - 10/15/2021, 6:09:35 PM   ERROR [ExceptionsHandler] Module did not self-register: '/Users/zhaopeng06/Documents/code/kuaishou/yoda-backstage/node_modules/bsdiff-node/build/Release/bsdiff.node'.
Error: Module did not self-register: '/Users/zhaopeng06/Documents/code/kuaishou/yoda-backstage/node_modules/bsdiff-node/build/Release/bsdiff.node'.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/zhaopeng06/Documents/code/kuaishou/yoda-backstage/node_modules/bsdiff-node/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

probably related to [#21783](https://github.com/nodejs/node/issues/21783#issuecomment-429637117)?

**Comment by Brouilles** [comment]
Can you create a minimal reproduction project?

**Comment by zpbc007** [comment]
It works, thanks a lot~

**Comment by Brouilles** [comment]
Great. I merge it soon in master and release a new version.

**Comment by Brouilles** [comment]
2.4.0 now available on npm.
